id: 0becb322b5904563bc6b2e28e47a5052
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_729-Dh%C4%81ra%E1%B9%87%C4%AB_of_T%C4%81r%C4%81-v2
  language: en
  author: ''
  volume: {}
